common_required_packages:
  - "gpg"
  - "jq"
  - "unzip"
  - "wget"
  - "git"
  - "python3-pip"
  - "python3-setuptools"
nodejs_gpg_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
nodejs_apt_repo: deb https://deb.nodesource.com/node_18.x jammy main
build_cicd_tool_packages:
  - "terraform"
  - "nodejs"
