---
- name: Update server
  hosts: ap-s1
  become: yes
  become_method: sudo
  vars_files:
    - host_vars/ap-s1.yml

  tasks:
    - name: 1. Update OS
      command: apt update

    - name: 2. Update package repository
      command: apt-get update -y

    - name: 3. Install ca-certificates
      apt:
        name: ca-certificates
        state: present
        force_apt_get: yes 

    - name: 4. Install software properties common
      apt: 
        name: software-properties-common 
        state: present
        force_apt_get: yes

    - name: 5. Add the intermediate certificate to certificate bundle
      command: update-ca-certificates

    - name: 6. Install aptitude using apt
      apt: 
        name: aptitude 
        state: present
        force_apt_get: yes

    - name: 7. Install common required system packages
      apt:
        name: "{{ common_required_packages }}"
        state: present
        force_apt_get: yes